In [2]:
import numpy as np

In [3]:
# creating array using in build method
arr1 = np.zeros((2,3), dtype="int64")
print(arr1,arr1.shape) 
# this is called prefill

arr1 = np.ones((7,30), dtype="int64")
print(arr1,arr1.shape)


arr1 = np.full((3,4),100)
print(arr1,arr1.shape)#this is prefill with value

arr1 = np.eye(3)
print(arr1,arr1.shape)#this is  called identical metricx



arr = np.arange(1,20,1)
print(arr,arr.shape)#this is  

arr = np.linspace(1,200,5)
print(arr,arr.shape)#this is

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]] (7, 30)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] (19,)
[  1.    50.75 100.5  150.25 200.  ] (5,)


In [ ]:
# now learning about array properties
arr = np.array([1,2,4,5,6,7,8,9,0])
print(arr.shape)
print (arr.size)
print (arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr , float_arr.dtype)