In [5]:
import numpy as np


In [23]:
arr = np.array([1,2,3,4,5,6,7])
print(arr, type(arr), arr.dtype,arr.shape)

arr2 = np.array([1,2,3,4,5,6,7,"kunal"])
print(arr2, type(arr2) ,arr2.dtype, arr2.shape )

arr2d = np.array([[1,3,4],[1,3,4],[1,3,4]])
print(arr2d ,arr2d.dtype)

[1 2 3 4 5 6 7] <class 'numpy.ndarray'> int64 (7,)
['1' '2' '3' '4' '5' '6' '7' 'kunal'] <class 'numpy.ndarray'> <U21 (8,)
[[1 3 4]
 [1 3 4]
 [1 3 4]] int64
